name: Waka Readme

on:
  schedule:
    # Runs every hour
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Profile Settings
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          
          # Customization
          LOCALE: "en"
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          
          # Display specific stats
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          
          # Remove Timeline (it's disabled by default, but ensuring it's off)
          SHOW_COMMIT_GRAPH: "False"
          
          # Theme Customization - Uncomment ONE theme below:
          
          # Dark Themes
          # THEME: "dark"
          # THEME: "radical"
          # THEME: "merko"
          # THEME: "gruvbox"
          # THEME: "tokyonight"
          # THEME: "onedark"
          # THEME: "cobalt"
          # THEME: "synthwave"
          # THEME: "dracula"
          THEME: "monokai"
          
          # Light Themes
          # THEME: "default"
          # THEME: "solarized-light"
          # THEME: "github"
          
          # Colorful Themes
          # THEME: "vue"
          # THEME: "react"
          # THEME: "chartreuse-dark"
          # THEME: "highcontrast"
          
          # Custom Color Scheme (Advanced)
          # Uncomment and customize these for full control:
          # COLOR_NAME_0: "#2f80ed"      # Title color
          # COLOR_NAME_1: "#52616b"      # Text color
          # COLOR_NAME_2: "#1e2022"      # Background color
          # COLOR_NAME_3: "#a4a4a4"      # Subtitle color
          # COLOR_NAME_4: "#646464"      # Secondary text color
          
          # Show detailed time tracking
          SHOW_TOTAL_TIME: "True"
