name: Waka Readme

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # ============ THEME (UNCOMMENTED - ACTIVE) ============
          THEME: "monokai"
          
          # ============ WHAT TO SHOW ============
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          
          # ============ WHAT TO HIDE ============
          # Remove Timeline/Commit Graph
          SHOW_COMMIT_GRAPH: "False"
          
          # ============ TIME TRACKING ============
          SHOW_TOTAL_TIME: "True"
          
          # ============ CUSTOMIZATION ============
          LOCALE: "en"
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          
          # ============ OTHER THEME OPTIONS (Change THEME above to use these) ============
          # Dark Themes: "dark", "radical", "merko", "gruvbox", "tokyonight", 
          #              "onedark", "cobalt", "synthwave", "dracula", "monokai"
          # Light Themes: "default", "solarized-light", "github"
          # Colorful: "vue", "react", "chartreuse-dark", "highcontrast"
