name: Waka Readme

on:
  schedule:
    # Runs at 12am IST (6:30 PM UTC)
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Profile Settings
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          
          # Customization
          LOCALE: "en"
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          
          # Display specific stats
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          
          # Remove Timeline (it's disabled by default, but ensuring it's off)
          SHOW_COMMIT_GRAPH: "False"
          
          # Color customization (optional - uncomment to use)
          # THEME: "radical"
          
          # Show detailed time tracking
          SHOW_TOTAL_TIME: "True"
